Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: ng
    SupplierDeployMetadata:
      RoleName: ${RoleName}
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: nginx
          Url: 'templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 1c1g
              Parameters:
                Vcpu: "1"
                Memory: 1Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
            - Name: 基础版
              Description: 2c2g
              Parameters:
                Vcpu: "2"
                Memory: 2Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
            - Name: 高配版
              Description: 2c4g
              Parameters:
                Vcpu: "2"
                Memory: 4Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
          HiddenParameterKeys:
            - ClusterId
            - Vcpu
            - Memory
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - ClusterId
              ParameterValueMapping:
                ${RegionId}:
                  Parameters:
                    ClusterId: ${ClusterId}
    TemplateConfigs:
      - Name: nginx
        AllowedRegions:
          - ${RegionId}
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: nginx kubeblocks ACK容器多租户
    Image: 'icons/service_logo.png'
    Name: nginx kubeblocks ACK容器yaml部署
  ShareType: Public
  ApprovalType: Manual